// js/words.js
// Each entry: { id, es, en, pos, example }
// pos: noun | verb | adj | adv
// example: sentence using the word (Spanish), with the word present

export const WORDS = [
  { id: 'w001', es: 'amanecer',   en: 'dawn',        pos: 'noun', example: 'El amanecer pintó el cielo de naranja.' },
  { id: 'w002', es: 'anochecer',  en: 'dusk',        pos: 'noun', example: 'Al anochecer, encendieron las lámparas.' },
  { id: 'w003', es: 'asombrar',   en: 'to amaze',    pos: 'verb', example: 'Su talento siempre logra asombrar al público.' },
  { id: 'w004', es: 'balbucear',  en: 'to babble',   pos: 'verb', example: 'El bebé empezó a balbucear sus primeras palabras.' },
  { id: 'w005', es: 'bisagra',    en: 'hinge',       pos: 'noun', example: 'La bisagra de la puerta chirriaba.' },
  { id: 'w006', es: 'brecha',     en: 'gap',         pos: 'noun', example: 'Existe una gran brecha entre los salarios.' },
  { id: 'w007', es: 'bullicio',   en: 'hustle',      pos: 'noun', example: 'Me encanta el bullicio del mercado.' },
  { id: 'w008', es: 'cansancio',  en: 'weariness',   pos: 'noun', example: 'El cansancio se notaba en su mirada.' },
  { id: 'w009', es: 'capricho',   en: 'whim',        pos: 'noun', example: 'Compró el sombrero por puro capricho.' },
  { id: 'w010', es: 'caricia',    en: 'caress',      pos: 'noun', example: 'Le dio una suave caricia en la mejilla.' },
  { id: 'w011', es: 'ceniza',     en: 'ash',         pos: 'noun', example: 'Las cenizas del fuego cubrieron el suelo.' },
  { id: 'w012', es: 'cima',       en: 'summit',      pos: 'noun', example: 'Llegaron a la cima de la montaña al mediodía.' },
  { id: 'w013', es: 'cobijo',     en: 'shelter',     pos: 'noun', example: 'El árbol nos dio cobijo de la lluvia.' },
  { id: 'w014', es: 'codicia',    en: 'greed',       pos: 'noun', example: 'La codicia lo llevó a tomar malas decisiones.' },
  { id: 'w015', es: 'consuelo',   en: 'comfort',     pos: 'noun', example: 'Sus palabras fueron un gran consuelo para mí.' },
  { id: 'w016', es: 'cordura',    en: 'sanity',      pos: 'noun', example: 'Mantuvo la cordura en momentos de crisis.' },
  { id: 'w017', es: 'desamparo',  en: 'helplessness',pos: 'noun', example: 'Sentía un profundo desamparo tras la pérdida.' },
  { id: 'w018', es: 'descanso',   en: 'rest',        pos: 'noun', example: 'Después del trabajo necesitaba un descanso.' },
  { id: 'w019', es: 'descuido',   en: 'oversight',   pos: 'noun', example: 'Por descuido dejó las llaves en la puerta.' },
  { id: 'w020', es: 'desenlace',  en: 'outcome',     pos: 'noun', example: 'El desenlace de la novela fue sorprendente.' },
  { id: 'w021', es: 'desvelo',    en: 'sleeplessness', pos: 'noun', example: 'El desvelo le afectó durante la presentación.' },
  { id: 'w022', es: 'dulzura',    en: 'sweetness',   pos: 'noun', example: 'Habló con una dulzura que me tranquilizó.' },
  { id: 'w023', es: 'elogiar',    en: 'to praise',   pos: 'verb', example: 'El maestro se detuvo a elogiar su trabajo.' },
  { id: 'w024', es: 'empeño',     en: 'determination', pos: 'noun', example: 'Logró el objetivo gracias a su empeño.' },
  { id: 'w025', es: 'encrucijada', en: 'crossroads', pos: 'noun', example: 'Estaba en una encrucijada y no sabía qué decidir.' },
  { id: 'w026', es: 'ensimismado', en: 'absorbed',   pos: 'adj',  example: 'Estaba tan ensimismado que no oyó el timbre.' },
  { id: 'w027', es: 'escasez',    en: 'scarcity',    pos: 'noun', example: 'La escasez de agua afecta a muchas regiones.' },
  { id: 'w028', es: 'estruendo',  en: 'loud noise',  pos: 'noun', example: 'El estruendo del trueno nos despertó.' },
  { id: 'w029', es: 'exhalar',    en: 'to exhale',   pos: 'verb', example: 'Exhaló profundamente antes de responder.' },
  { id: 'w030', es: 'fardo',      en: 'bundle',      pos: 'noun', example: 'Llevaba un fardo de leña sobre los hombros.' },
  { id: 'w031', es: 'fervor',     en: 'fervor',      pos: 'noun', example: 'Defendió su postura con fervor.' },
  { id: 'w032', es: 'flaqueza',   en: 'weakness',    pos: 'noun', example: 'La impaciencia era su mayor flaqueza.' },
  { id: 'w033', es: 'fugaz',      en: 'fleeting',    pos: 'adj',  example: 'Fue un encuentro fugaz pero memorable.' },
  { id: 'w034', es: 'fulgor',     en: 'brilliance',  pos: 'noun', example: 'El fulgor de las estrellas iluminó la noche.' },
  { id: 'w035', es: 'hastío',     en: 'boredom',     pos: 'noun', example: 'El hastío de la rutina lo agotaba.' },
  { id: 'w036', es: 'hazaña',     en: 'feat',        pos: 'noun', example: 'Cruzar el desierto fue una verdadera hazaña.' },
  { id: 'w037', es: 'holgura',    en: 'ease',        pos: 'noun', example: 'Vivían con cierta holgura económica.' },
  { id: 'w038', es: 'indicio',    en: 'clue',        pos: 'noun', example: 'No había ningún indicio de lo ocurrido.' },
  { id: 'w039', es: 'ímpetu',     en: 'impetus',     pos: 'noun', example: 'Atacó la tarea con gran ímpetu.' },
  { id: 'w040', es: 'lazo',       en: 'bond',        pos: 'noun', example: 'El lazo entre hermanos es muy especial.' },
  { id: 'w041', es: 'leve',       en: 'slight',      pos: 'adj',  example: 'Sintió un leve mareo al levantarse.' },
  { id: 'w042', es: 'llanura',    en: 'plain',       pos: 'noun', example: 'Las vacas pastaban en la llanura.' },
  { id: 'w043', es: 'madrugada',  en: 'early hours', pos: 'noun', example: 'Llegó a casa en la madrugada.' },
  { id: 'w044', es: 'maleza',     en: 'undergrowth', pos: 'noun', example: 'El camino estaba cubierto de maleza.' },
  { id: 'w045', es: 'mansedumbre', en: 'meekness',   pos: 'noun', example: 'Aceptó la crítica con mansedumbre.' },
  { id: 'w046', es: 'maraña',     en: 'tangle',      pos: 'noun', example: 'Una maraña de cables llenaba el cuarto.' },
  { id: 'w047', es: 'murmullo',   en: 'murmur',      pos: 'noun', example: 'El murmullo del río me ayudó a dormir.' },
  { id: 'w048', es: 'nostalgia',  en: 'nostalgia',   pos: 'noun', example: 'La canción le trajo mucha nostalgia.' },
  { id: 'w049', es: 'orgullo',    en: 'pride',       pos: 'noun', example: 'Habló de su hijo con mucho orgullo.' },
  { id: 'w050', es: 'pavor',      en: 'dread',       pos: 'noun', example: 'Sentía pavor ante la oscuridad total.' },
  { id: 'w051', es: 'pesar',      en: 'sorrow',      pos: 'noun', example: 'Expresó su pesar por la noticia.' },
  { id: 'w052', es: 'pudor',      en: 'modesty',     pos: 'noun', example: 'Lo dijo con cierto pudor.' },
  { id: 'w053', es: 'rencor',     en: 'resentment',  pos: 'noun', example: 'Guardaba rencor desde hace años.' },
  { id: 'w054', es: 'rezagar',    en: 'to fall behind', pos: 'verb', example: 'No quería rezagarse del grupo.' },
  { id: 'w055', es: 'rumbo',      en: 'course',      pos: 'noun', example: 'El barco cambió de rumbo repentinamente.' },
  { id: 'w056', es: 'senda',      en: 'path',        pos: 'noun', example: 'Siguieron la senda a través del bosque.' },
  { id: 'w057', es: 'sigilo',     en: 'stealth',     pos: 'noun', example: 'Se movió con sigilo para no despertar a nadie.' },
  { id: 'w058', es: 'sosiego',    en: 'calm',        pos: 'noun', example: 'Encontró sosiego en la naturaleza.' },
  { id: 'w059', es: 'umbral',     en: 'threshold',   pos: 'noun', example: 'Se detuvo en el umbral de la puerta.' },
  { id: 'w060', es: 'vaivén',     en: 'swaying',     pos: 'noun', example: 'El vaivén del tren lo adormecía.' },
];
